version: '3'
services:
  selenium-server:
    image: selenium/hub:3.141.59
    ports:
      - 4444:4444
    environment:
      - GRID_MAX_SESSION=1
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 5
  selenium-chrome:
    image: selenium/node-chrome-debug:3.141.59
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-server
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    ports:
      - 5900:5900
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:5555"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: none
    depends_on:
      - selenium-server
    shm_size: 2g